# Generated by Django 2.1 on 2019-07-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190724_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='review',
            name='longitude',
        ),
    ]
